version: '3.8'

services:
  web:
    build: .
    expose:
      - 5001
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-dev-key}
      - NEST_CLIENT_ID=${NEST_CLIENT_ID}
      - NEST_CLIENT_SECRET=${NEST_CLIENT_SECRET}
      - NEST_REFRESH_TOKEN=${NEST_REFRESH_TOKEN}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf.template
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      - DOMAIN=${DOMAIN}
    command: /bin/sh -c "envsubst '$$DOMAIN' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge

volumes:
  data: