version: '3.8'

services:
  web:
    image: house-temp-tracker:latest
    ports:
      - "5003:5001"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-dev-key}
      - NEST_CLIENT_ID=${NEST_CLIENT_ID}
      - NEST_CLIENT_SECRET=${NEST_CLIENT_SECRET}
      - NEST_REFRESH_TOKEN=${NEST_REFRESH_TOKEN}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - proxy-network

  cron:
    image: house-temp-tracker:latest
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-dev-key}
      - NEST_CLIENT_ID=${NEST_CLIENT_ID}
      - NEST_CLIENT_SECRET=${NEST_CLIENT_SECRET}
      - NEST_REFRESH_TOKEN=${NEST_REFRESH_TOKEN}
    volumes:
      - ./data:/app/data
      - ./crontab:/etc/cron.d/collect-data
    command: /bin/sh -c "chmod 0644 /etc/cron.d/collect-data && crontab /etc/cron.d/collect-data && cron && tail -f /var/log/cron.log"
    restart: unless-stopped
    depends_on:
      - web

networks:
  proxy-network:
    external: true

volumes:
  data: